site_name: B2Bi Usecases 
theme:
  name: material
  language: en
  favicon: assets/b2bi.png
  logo: assets/logo.png
  features:
    - tabs
    - instant
    - navigation.tabs
markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Event-Driven MFT: event-driven-mft-b2b/README.md
  - B2Bi-Generate-835: healthcare-generate-835/README.md
